add_newline = false # Don't print a new line at the start of the prompt

[character]
success_symbol = "[➜ ](bold green)"
error_symbol = "[✗](bold red)"
use_symbol_for_status = true

[battery]
disabled = true

# [memory_usage]
# disabled = false
# show_percentage = true
# show_swap = true
# threshold = -1
# symbol = " "
# separator = "/"
# style = "bold dimmed green"
