#!/bin/sh

# use neovim instead of vi and vim
alias\
	v="nvim"\
	vi="nvim"\
	vim="nvim"\
	vimdiff="nvim -d"

# Verbosity settings for main utilities
alias\
	cp="cp -iv"\
	mv="mv -iv"\
	rm="trash"\
	mkd="mkdir -pv"\
	yt="youtube-dl --add-metadata -i"\
	ffmpeg="ffmpeg -hide_banner"

# Colorize commands when possible
alias\
	ls="exa -l --color=always --group-directories-first"\
	la="exa -al --color=always --group-directories-first"\
	l.="exa -a | egrep\"^\.\""\
	l="ls"\
	tree="exa -aT --color=always --group-directories-first"\
	grep="grep --color=auto"\
	diff="diff --color=auto"\
	ccat="highlight --out-format=ansi"

# Git Commands
alias\
	g="git"\
	init="echo '#' >> README.md && g init && g add ."\
	addup="g add -u"\
	addall="g add ."\
	branch="g branch"\
	checkout="g checkout"\
	clone="g clone"\
	commit="g commit"\
	fetch="g fetch"\
	pull="g pull origin"\
	push="g push origin"\
	status="g status"\
	tag="g tag"\
	newtag="g tag -a"

# Pacman Commands
alias\
	p="pacman"\
	sp="sudo p"\
	checkcache="sudo ls /var/cache/pacman/pkg/"\
	checkcachecount="sudo ls /var/cache/pacman/pkg/ | wc -l"\
	checkcachedisksize="sudo du -sh /var/cache/pacman/pkg/"\
	cleancache="sp -Scc"\
	cleanorphans="sp -Qtdq | sp -Rns -"

# Hard to type or just to long to type commands
alias\
	k="kill"\
	ka="killall"\
	f="$FILE"\
	z="zathura"\
	e="neomutt"\
	f="ranger"\
	s="sxiv"\
	S="sudo"\
	updategrubconfig="sudo grub-mkconfig -o /boot/grub/grub.cfg"\
	refreshdwmblocks="killall -q dwmblocks;setsid dwmblocks &"\
	syncmails="mw -Y && pkill -RTMIN+9 dwmblocks && e"\
	syncmonero="monerod --data-dir ~/hell/monero --prune-blockchain"

# Add settings to programs
alias\
	abook="abook -C \"$XDG_CONFIG_HOME\"/abook/abookrc --datafile \"$XDG_DATA_HOME\"/abook/addressbook"\
	mp3="youtube-dl -f bestaudio --extract-audio --audio-format mp3 --audio-quality 5"\
	mp4="youtube-dl -f 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/bestvideo+bestaudio' --merge-output-format mp4"

# Suffix Zsh Aliases
alias -s {py,go,html,css,js,md,c,h,cpp,tex}="nvim"

# Global Aliases
alias -g\
	na="neoakintito"\
	suckmore="~/.local/src/suckless/ && l"\
	classes="~/hell/ASOEE/classes/ && l"\
	opa="~/hell/ASOEE && l"\
	opapy="~/hell/ASOEE/classes/PROG/ && l"\
	opacs="~/hell/ASOEE/classes/CS/ && l"\
	opamath="~/hell/ASOEE/classes/MATH/ && l"\
	htdocs="/opt/lampp/htdocs/ && l"

# Helper Functions
ss() { find ~/.local ~/.config | fzf | xargs -r $EDITOR ; }
vf() { fzf | xargs -r -I % $EDITOR % ; }
compress_mp4() { ffmpeg -i $1 -vcodec libx265 -crf 28 $2 ; }
