#!/bin/zsh

# Use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias\
	v="nvim"\
	vi="nvim"\
	vim="nvim"\
	vimdiff="nvim -d"

# Verbosity settings for main utilities
alias\
	cp="cp -iv"\
	mv="mv -iv"\
	mkd="mkdir -pv"\
	yt="youtube-dl --add-metadata -i"\
	ffmpeg="ffmpeg -hide_banner"

# Colorize commands when possible
alias\
	ls="exa -l --color=always --group-directories-first"\
	la="exa -al --color=always --group-directories-first"\
	l.="exa -a | egrep\"^\.\""\
	l="ls"\
	tree="exa -aT --color=always --group-directories-first"\
	grep="grep --color=auto"\
	diff="diff --color=auto"\
	ccat="highlight --out-format=ansi"

# Git Commands
alias\
	g="git"\
	init="echo '#' >> README.md && g init && g add ."\
	addup="g add -u"\
	addall="g add ."\
	branch="g branch"\
	checkout="g checkout"\
	clone="g clone"\
	commit="g commit"\
	fetch="g fetch"\
	pull="g pull origin"\
	push="g push origin"\
	status="g status"\
	tag="g tag"\
	newtag="g tag -a"

# Pacman Commands
alias\
	p="pacman"\
	sp="sudo pacman"\
	yay="paru"\
	checkcache="sudo ls /var/cache/pacman/pkg/"\
	checkcachecount="sudo ls /var/cache/pacman/pkg/ | wc -l"\
	checkcachedisksize="sudo du -sh /var/cache/pacman/pkg/"\
	cleancache="sp -Scc"\
	cleanorphans="sp -Qtdq | sp -Rns -"

# cmd trash Commands
alias\
	Rm="rm"\
	RM="rm -rf"\
	rm="trash"\
	te="trash-empty"\
	tl="trash-list"\
	tR="trash-restore"

# Hard to type or just to long to type commands
alias\
	k="kill"\
	ka="killall"\
	f="$FILE"\
	z="zathura"\
	e="neomutt"\
	f="ranger"\
	s="sxiv"\
	S="sudo"\
	cntd="exa -1 . | wc -l"\
	cntD="exa -1 -a . | wc -l"\
	updatefontcache="fc-cache -f -v"\
	updategrubconfig="sudo grub-mkconfig -o /boot/grub/grub.cfg"\
	refreshdwmblocks="killall -q dwmblocks;setsid dwmblocks &"\
	hardrefreshdwmblocks="killall -q dwmblocks;rm -rf ~/.local/share/weatherreport ~/.local/share/crypto-prices;setsid dwmblocks &"\
	syncmails="mw -Y && pkill -RTMIN+9 dwmblocks && e"\
	news="newsboat && pkill -RTMIN+16 dwmblocks"\
	power_stats="sudo tlp-stat"\
	datestamp="date '+%F'"

# Add settings to programs
alias\
	abook="abook -C \"$XDG_CONFIG_HOME\"/abook/abookrc --datafile \"$XDG_DATA_HOME\"/abook/addressbook"\
	mp3="youtube-dl -f bestaudio --extract-audio --audio-format mp3 --audio-quality 5"\
	mp4="youtube-dl -f 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/bestvideo+bestaudio' --merge-output-format mp4"\
	monerod="monerod --data-dir /media/monero --bg-mining-enable"\
	monero-wallet-cli="monero-wallet-cli --wallet-file /media/monero/nosmaney"\
	shred="shred -ufvz -n 5"

# Suffix Zsh Aliases
alias -s {py,go,html,css,js,md,c,h,cpp,tex}="nvim"

# Global Aliases
alias -g\
	na="neoakintito"\
	suckmore="~/.local/src/suckless/ && l"\
	classes="~/hell/ASOEE/classes/ && l"\
	opa="~/hell/ASOEE && l"\
	htdocs="/opt/lampp/htdocs/ && l"

# Helper Functions
ss() { find ~/.local/bin/scripts/ ~/.local/share/ ~/.config | fzf | xargs -r $EDITOR }
vf() { fzf | xargs -r -I % $EDITOR % }
x+()  { chmod +x $1 }
x-()  { chmod -x $1 }
cs_mp4()  { ffmpeg -i $1 -vcodec libx265 -crf 28 $2 }
cs_zip()  { zip -r "$1.zip" $1 }
# cs_gzip() {}
# cs_xz()   {}
# cs_7z()   {}
# cs_rar()  {}
a_tar()   { tar -cf $1 $2 }
crop_to_content() { convert $1 -flatten -fuzz 1% -trim +repage $2 }
gen_passwd() { gpg --gen-random --armor 1 "${1:-12}" }
basehdd() { (lsblk -f > /dev/null 2>&1 | grep 'ad096952-5bfc-4d02-bdbe-184b31ce632b'>/dev/null 2>&1) && (df -h >/dev/null 2>&1 | grep 'basehdd'>/dev/null 2>&1 && (sudo umount /media/basehdd && notify-send 'basehdd umounted.') || (sudo mount --uuid 'ad096952-5bfc-4d02-bdbe-184b31ce632b' /media/basehdd && notify-send 'basehdd mounted.')) }
