#!/bin/sh

# profile file, runs on login. Env vars are set here.

# Add ~/.local/bin to $PATH
export PATH="$PATH:/home/manos/.local/bin:/home/manos/.local/bin/scripts:/home/manos/.local/bin/scripts/statusbar:/opt/lampp:/opt/lampp/bin/"

# Default Programs:
export EDITOR="nvim"
export TERMINAL="st"
export BROWSER="brave"

# ~/ Clean-up:
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
export XINITRC="${XDG_CONFIG_HOME:-$HOME/.config}/x11/xinitrc"
export XAUTHORITY="$XDG_RUNTIME_DIR/Xauthority" # This line will break some DMs (but not dwm)
export LESSHISTFILE="-"
export GTK2_RC_FILES="${XDG_CONFIG_HOME:-$HOME/.config}/gtk-2.0/gtkrc-2.0"
export WGETRC="${XDG_CONFIG_HOME:-$HOME/.config}/wget/wgetrc"
export INPUTRC="${XDG_CONFIG_HOME:-$HOME/.config}/sh/inputrc"
export ZDOTDIR="${XDG_CONFIG_HOME:-$HOME/.config}/zsh"
export GOPATH="$HOME/.local/src/golang"
export HISTFILE="${XDG_DATA_HOME:-$HOME/.local/share}/history"
# export DBUS_SESSION_BUS_ADDRESS='unix:abstract=/tmp/dbus-a7hUEojAOw,guid=b068e6cf65b1d28da033e46f5fbc0ce7'
export GNUPGHOME="$XDG_DATA_HOME/gnupg"
export PASSWORD_STORE_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/password-store"
export NOTMUCH_CONFIG="$XDG_CONFIG_HOME/notmuch/notmuchrc"
export NMBGIT="$XDG_DATA_HOME/notmuch/nmbug"
export NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME/npm/npmrc"
export MBSYNCRC="$XDG_CONFIG_HOME/mbsync/mbsyncrc"
export PYTHONSTARTUP="$XDG_CONFIG_HOME/python/pythonstartup"
export NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME/npm/npmrc"
export CARGO_HOME="$XDG_DATA_HOME/cargo"
export _JAVA_AWT_WM_NONREPARENTING=1

# Other program settings:
export SUDO_ASKPASS="$HOME/.local/bin/scripts/dmenuaskpass"
export FZF_DEFAULT_OPTS="--layout=reverse --height 40%"
export LESS=-R

[ ! -f ${XDG_CONFIG_HOME:-$HOME/.config}/shell/shortcutrc ] && shortcuts > /dev/null 2>&1 &

# if pacman -Qs libxft-bgra > /dev/null 2>&1; then
# 	# Start graphical server on user's current tty if not already running
# 	[ "$(tty)" = "/dev/tty1" ] && ! pidof -s Xorg > /dev/null 2>&1 && exec startx
# else
# 	echo "\033[31mIMPORTANT\033[0m: Note that \033[32m\`libxft-bgra\`\033[0m must be installed for dwm.
# 	Please run:
# 		\033[32myay -S libxft-bgra-git ttf-joypixels\033[0m
# 	and replace \`libxft\`. Afterwards, restart the graphical server with \`startx\`."
# fi

# Switch escape and caps if tty and no passwd required.
# sudo -n loadkeys $HOME/.local/share/ttymaps.kmap 2>/dev/null
if [ -z "${DISPLAY}" ] && [ ${XDG_VTNR} -eq 1 ]; then
	exec startx "$XINITRC"
fi
