#!/usr/bin/env bash


for file in Xresources-themes/*; do
	echo "
/* !! Transparency (0-1): */
*.alpha: 0.8
/* !! Set a default font and font size as below: */
*.font: FantasqueSansMono Nerd Font Mono:size=10
" >> $file
done
