#!/bin/sh

# xinitrc runs automatically when you startx.
# .xprofile functionallity is built in the dwm binary.
# exec dbus-launch --sh-syntax --exit-with-session dwm # runit

# eval $(/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh)
export SSH_AUTH_SOCK=$(gpgconf --list-dirs agent-ssh-socket)

while true
do
	ssh-agent dwm 2> /home/manos/.local/logs/dwm.log
done
