#!/bin/sh

# This file runs when a DM logs you into a graphical session.

# dbus-launch &		# launch dbus (used by gnome-keyring, xcomprmgr, ..)
xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources & 	# xresources color settings on startup
gnome-keyring-daemon --start --components=secrets & 		# safe password automatically for apps like skype, etc.
# remaps &		# remaps script
dunst & 		# notifications
# xcompmgr &		# desktop transparency effects
xset r rate 300 50 & 	# Speed xrate up
unclutter & 		# Hide mouse when idle
